### ISSUE TITLE
Application crash after selecting done button.

### ISSUE THREAD

**Issue by juniorba** [eman1986/TimOliver.TOCropViewController.Xamarin#1]
Hello,

Application crash after selecting done button.

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIImage croppedImageWithFrame:angle:circularClip:]: unrecognized selector sent to instance 0x280cd0d20

thanks,
Jr.

**Comment by eman1986** [comment]
let me see if I can reproduce that on the sample app, if not, I'll need more information from you.

**Comment by felipechavez** [comment]
same here, tested with the sample app

**Comment by eman1986** [comment]
I just ran the sample app the other day when I updated to the newest version, could you explain more on what you did to cause it to crash? was there a specific setting you had set for example?

**Comment by felipechavez** [comment]
sure, well. probably is a miss configuration on my code or something bad implemented. [Here is an implementation](https://github.com/felipechavez/ImageCropper.Forms/blob/master/ImageCropper/ImageCropper.iOS/ImageCropperImplementation.cs). In my test example i just press done and this exception appear. Can you help me on how can I solve this?

**Comment by felipechavez** [comment]
I just installed the test application of your project and the same thing happens.

**Comment by eman1986** [comment]
Thanks for these details, I'll play around with the sample app and try to reproduce the issue.

**Comment by giuseppenovielli** [comment]
@eman1986 try to add these line of code into assembly file:

(rename name of static library .a file)

[assembly: LinkWith ("libIQKeyboardManager.a", LinkTarget.Simulator | LinkTarget.ArmV7 | LinkTarget.Arm64, ForceLoad = true, SmartLink=true, LinkerFlags = "-ObjC" )]

**Comment by eman1986** [comment]
Thanks, I need to update to the newest version, I'll apply this when I get to that.

**Comment by eman1986** [comment]
I updated the binding to the newest version and I applied the linking fix @giuseppenovielli sugggested, this should be resolved.

**Comment by giuseppenovielli** [comment]
@eman1986 Thanks for maintening Binding!!

**Comment by eman1986** [comment]
Thank you for helping me figure out the issue with the linking
